# Copyright (C) 2018-2023 Mark McIntyre
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "matchDataApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cy2k1achj9nv"
s3_prefix = "matchDataApi"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
profile = "ukmda_admin"
