version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fetchECSV"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17e011f5cwvp1"
s3_prefix = "fetchECSV"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
